#docker compose services

version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wp-content:/var/www/html/wp-content
    restart: always
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: adminpass
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - 3306:3306
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always

volumes:
  wp-content:
  data-mysql:

networks:
  default:
    driver: bridge


#docker compose up
#docker compose down
#docker compose logs -f
#docker compose exec wordpress bash


